name: Publish Nuget packages
description: build and test template

runs: 
  using: composite
  steps:
  - uses: actions/checkout@v2
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    shell: pwsh
  - name: Restore dependencies
    run: |
        dotnet restore --configfile 'nuget.config'
    shell: pwsh
  - name: Test
    run: dotnet test --collect='XPlat Code Coverage' --verbosity normal
    shell: pwsh
        
